#include "Device9.h"
#include <detours.h>
#include <tlhelp32.h>
using namespace Resource9;
// Native entry/exit nesting is evidence: a runtime-internal Surface.LockRect
// under Texture.LockRect need not have a Surface.UnlockRect API counterpart.
struct MapScope;
static thread_local MapScope* currentMap;
static LONG nextMapCall;
struct MapScope {
    MapScope* Previous;Item* Owner;LONG Id,Depth;const char* Api;
    MapScope(const char* api,Item* owner):Previous(currentMap),Owner(owner),Id(InterlockedIncrement(&nextMapCall)),Depth(Previous?Previous->Depth+1:1),Api(api){currentMap=this;Record("enter");}
    ~MapScope(){Record("exit");currentMap=Previous;}
    void Record(const char* direction){char name[100];sprintf_s(name,"map-call-%s-%s",direction,Api);Log(name,Owner,Id,Previous?Previous->Id:0,Depth);}
};
#include "MapPss.h"
struct Hook{void** Target;void* Replacement;const char* Name;};static std::vector<Hook> hooks;static bool installed;
template<class Fn>static void Set(Fn& real,void* address,void* replacement,const char* name){real=reinterpret_cast<Fn>(address);hooks.push_back({reinterpret_cast<void**>(&real),replacement,name});}
template<class T>static void** Table(T* object){return *reinterpret_cast<void***>(object);}
using TextureFn=HRESULT(WINAPI*)(IDirect3DDevice9*,UINT,UINT,UINT,DWORD,D3DFORMAT,D3DPOOL,IDirect3DTexture9**,HANDLE*);static TextureFn realTexture;
static HRESULT WINAPI Texture(IDirect3DDevice9* self,UINT w,UINT h,UINT levels,DWORD usage,D3DFORMAT format,D3DPOOL pool,IDirect3DTexture9** out,HANDLE* shared){HRESULT hr=realTexture(self,w,h,levels,usage,format,pool,out,shared);DWORD error=GetLastError();Item* item=SUCCEEDED(hr)&&out&&*out?Watch(*out,"texture9"):nullptr;Log("CreateTexture",item,static_cast<DWORD>(hr),(static_cast<uint64_t>(w)<<32)|h,(static_cast<uint64_t>(usage)<<32)|static_cast<UINT>(pool));SetLastError(error);return hr;}
using SurfaceFn=HRESULT(WINAPI*)(IDirect3DDevice9*,UINT,UINT,D3DFORMAT,D3DMULTISAMPLE_TYPE,DWORD,BOOL,IDirect3DSurface9**,HANDLE*);static SurfaceFn realTarget,realDepth;
static HRESULT SurfaceCall(SurfaceFn real,const char* api,const char* kind,IDirect3DDevice9* self,UINT w,UINT h,D3DFORMAT format,D3DMULTISAMPLE_TYPE sample,DWORD quality,BOOL option,IDirect3DSurface9** out,HANDLE* shared){HRESULT hr=real(self,w,h,format,sample,quality,option,out,shared);DWORD error=GetLastError();Item* item=SUCCEEDED(hr)&&out&&*out?Watch(*out,kind):nullptr;Log(api,item,static_cast<DWORD>(hr),(static_cast<uint64_t>(w)<<32)|h,format);SetLastError(error);return hr;}
static HRESULT WINAPI Target(IDirect3DDevice9* s,UINT w,UINT h,D3DFORMAT f,D3DMULTISAMPLE_TYPE m,DWORD q,BOOL b,IDirect3DSurface9** o,HANDLE* z){return SurfaceCall(realTarget,"CreateRenderTarget","render-target9",s,w,h,f,m,q,b,o,z);}
static HRESULT WINAPI Depth(IDirect3DDevice9* s,UINT w,UINT h,D3DFORMAT f,D3DMULTISAMPLE_TYPE m,DWORD q,BOOL b,IDirect3DSurface9** o,HANDLE* z){return SurfaceCall(realDepth,"CreateDepthStencilSurface","depth9",s,w,h,f,m,q,b,o,z);}
using PlainFn=HRESULT(WINAPI*)(IDirect3DDevice9*,UINT,UINT,D3DFORMAT,D3DPOOL,IDirect3DSurface9**,HANDLE*);static PlainFn realPlain;
static HRESULT WINAPI Plain(IDirect3DDevice9* s,UINT w,UINT h,D3DFORMAT f,D3DPOOL pool,IDirect3DSurface9** out,HANDLE* shared){HRESULT hr=realPlain(s,w,h,f,pool,out,shared);DWORD error=GetLastError();Item* item=SUCCEEDED(hr)&&out&&*out?Watch(*out,"plain-surface9"):nullptr;Log("CreateOffscreenPlainSurface",item,static_cast<DWORD>(hr),(static_cast<uint64_t>(w)<<32)|h,pool);SetLastError(error);return hr;}
using VertexFn=HRESULT(WINAPI*)(IDirect3DDevice9*,UINT,DWORD,DWORD,D3DPOOL,IDirect3DVertexBuffer9**,HANDLE*);static VertexFn realVertex;
static HRESULT WINAPI Vertex(IDirect3DDevice9* s,UINT bytes,DWORD usage,DWORD fvf,D3DPOOL pool,IDirect3DVertexBuffer9** out,HANDLE* shared){HRESULT hr=realVertex(s,bytes,usage,fvf,pool,out,shared);DWORD error=GetLastError();Item* item=SUCCEEDED(hr)&&out&&*out?Watch(*out,"vertex-buffer9"):nullptr;Log("CreateVertexBuffer",item,static_cast<DWORD>(hr),bytes,(static_cast<uint64_t>(usage)<<32)|pool);SetLastError(error);return hr;}
using IndexFn=HRESULT(WINAPI*)(IDirect3DDevice9*,UINT,DWORD,D3DFORMAT,D3DPOOL,IDirect3DIndexBuffer9**,HANDLE*);static IndexFn realIndex;
static HRESULT WINAPI Index(IDirect3DDevice9* s,UINT bytes,DWORD usage,D3DFORMAT format,D3DPOOL pool,IDirect3DIndexBuffer9** out,HANDLE* shared){HRESULT hr=realIndex(s,bytes,usage,format,pool,out,shared);DWORD error=GetLastError();Item* item=SUCCEEDED(hr)&&out&&*out?Watch(*out,"index-buffer9"):nullptr;Log("CreateIndexBuffer",item,static_cast<DWORD>(hr),bytes,(static_cast<uint64_t>(usage)<<32)|pool);SetLastError(error);return hr;}
using SurfaceExFn=HRESULT(WINAPI*)(IDirect3DDevice9Ex*,UINT,UINT,D3DFORMAT,D3DMULTISAMPLE_TYPE,DWORD,BOOL,IDirect3DSurface9**,HANDLE*,DWORD);static SurfaceExFn realTargetEx,realDepthEx;
static HRESULT SurfaceExCall(SurfaceExFn real,const char* api,const char* kind,IDirect3DDevice9Ex* s,UINT w,UINT h,D3DFORMAT f,D3DMULTISAMPLE_TYPE m,DWORD q,BOOL b,IDirect3DSurface9** out,HANDLE* shared,DWORD usage){HRESULT hr=real(s,w,h,f,m,q,b,out,shared,usage);DWORD error=GetLastError();Item* item=SUCCEEDED(hr)&&out&&*out?Watch(*out,kind):nullptr;Log(api,item,static_cast<DWORD>(hr),(static_cast<uint64_t>(w)<<32)|h,usage);SetLastError(error);return hr;}
static HRESULT WINAPI TargetEx(IDirect3DDevice9Ex* s,UINT w,UINT h,D3DFORMAT f,D3DMULTISAMPLE_TYPE m,DWORD q,BOOL b,IDirect3DSurface9** o,HANDLE* z,DWORD u){return SurfaceExCall(realTargetEx,"CreateRenderTargetEx","render-target9",s,w,h,f,m,q,b,o,z,u);}
static HRESULT WINAPI DepthEx(IDirect3DDevice9Ex* s,UINT w,UINT h,D3DFORMAT f,D3DMULTISAMPLE_TYPE m,DWORD q,BOOL b,IDirect3DSurface9** o,HANDLE* z,DWORD u){return SurfaceExCall(realDepthEx,"CreateDepthStencilSurfaceEx","depth9",s,w,h,f,m,q,b,o,z,u);}
using PlainExFn=HRESULT(WINAPI*)(IDirect3DDevice9Ex*,UINT,UINT,D3DFORMAT,D3DPOOL,IDirect3DSurface9**,HANDLE*,DWORD);static PlainExFn realPlainEx;
static HRESULT WINAPI PlainEx(IDirect3DDevice9Ex* s,UINT w,UINT h,D3DFORMAT f,D3DPOOL pool,IDirect3DSurface9** out,HANDLE* shared,DWORD usage){HRESULT hr=realPlainEx(s,w,h,f,pool,out,shared,usage);DWORD error=GetLastError();Item* item=SUCCEEDED(hr)&&out&&*out?Watch(*out,"plain-surface9"):nullptr;Log("CreateOffscreenPlainSurfaceEx",item,static_cast<DWORD>(hr),(static_cast<uint64_t>(w)<<32)|h,usage);SetLastError(error);return hr;}
using LevelFn=HRESULT(WINAPI*)(IDirect3DTexture9*,UINT,IDirect3DSurface9**);static LevelFn realLevel;
static HRESULT WINAPI Level(IDirect3DTexture9* s,UINT level,IDirect3DSurface9** out){HRESULT hr=realLevel(s,level,out);DWORD error=GetLastError();Item* parent=Find(s);Item* item=SUCCEEDED(hr)&&out&&*out?Watch(*out,"texture-surface9",parent?parent->Id:0):nullptr;Log("GetSurfaceLevel",item,static_cast<DWORD>(hr),level);SetLastError(error);return hr;}
using LockTextureFn=HRESULT(WINAPI*)(IDirect3DTexture9*,UINT,D3DLOCKED_RECT*,const RECT*,DWORD);static LockTextureFn realLockTexture;
using UnlockTextureFn=HRESULT(WINAPI*)(IDirect3DTexture9*,UINT);static UnlockTextureFn realUnlockTexture;
static void MapRecord(const char* api,Item* item,HRESULT hr,void* pointer,uintptr_t pitch,uintptr_t flags){Log(api,item,static_cast<DWORD>(hr),reinterpret_cast<uintptr_t>(pointer),pitch);if(SUCCEEDED(hr)&&pointer){MEMORY_BASIC_INFORMATION memory{};SIZE_T n=VirtualQuery(pointer,&memory,sizeof(memory));Log("mapped-va",item,n,(static_cast<uint64_t>(memory.State)<<32)|memory.Type,(static_cast<uint64_t>(memory.Protect)<<32)|flags);MapPss::Capture(api,item,pointer,pitch,static_cast<DWORD>(flags));}}
static HRESULT WINAPI LockTexture(IDirect3DTexture9* s,UINT level,D3DLOCKED_RECT* out,const RECT* rect,DWORD flags){MapScope scope("TextureLockRect",Find(s));HRESULT hr=realLockTexture(s,level,out,rect,flags);DWORD error=GetLastError();MapRecord("TextureLockRect",Find(s),hr,SUCCEEDED(hr)&&out?out->pBits:nullptr,SUCCEEDED(hr)&&out?out->Pitch:0,flags);SetLastError(error);return hr;}
static HRESULT WINAPI UnlockTexture(IDirect3DTexture9* s,UINT level){MapScope scope("TextureUnlockRect",Find(s));HRESULT hr=realUnlockTexture(s,level);DWORD error=GetLastError();Log("TextureUnlockRect",Find(s),static_cast<DWORD>(hr),level);SetLastError(error);return hr;}
using LockSurfaceFn=HRESULT(WINAPI*)(IDirect3DSurface9*,D3DLOCKED_RECT*,const RECT*,DWORD);static LockSurfaceFn realLockSurface;
using UnlockSurfaceFn=HRESULT(WINAPI*)(IDirect3DSurface9*);static UnlockSurfaceFn realUnlockSurface;
static LockSurfaceFn realLockPlain;static UnlockSurfaceFn realUnlockPlain;
static HRESULT WINAPI LockSurface(IDirect3DSurface9* s,D3DLOCKED_RECT* out,const RECT* rect,DWORD flags){MapScope scope("SurfaceLockRect",Find(s));HRESULT hr=realLockSurface(s,out,rect,flags);DWORD error=GetLastError();MapRecord("SurfaceLockRect",Find(s),hr,SUCCEEDED(hr)&&out?out->pBits:nullptr,SUCCEEDED(hr)&&out?out->Pitch:0,flags);SetLastError(error);return hr;}
static HRESULT WINAPI UnlockSurface(IDirect3DSurface9* s){MapScope scope("SurfaceUnlockRect",Find(s));HRESULT hr=realUnlockSurface(s);DWORD error=GetLastError();Log("SurfaceUnlockRect",Find(s),static_cast<DWORD>(hr));SetLastError(error);return hr;}
static HRESULT WINAPI LockPlain(IDirect3DSurface9* s,D3DLOCKED_RECT* out,const RECT* rect,DWORD flags){MapScope scope("SurfaceLockRect",Find(s));HRESULT hr=realLockPlain(s,out,rect,flags);DWORD error=GetLastError();MapRecord("SurfaceLockRect",Find(s),hr,SUCCEEDED(hr)&&out?out->pBits:nullptr,SUCCEEDED(hr)&&out?out->Pitch:0,flags);SetLastError(error);return hr;}
static HRESULT WINAPI UnlockPlain(IDirect3DSurface9* s){MapScope scope("SurfaceUnlockRect",Find(s));HRESULT hr=realUnlockPlain(s);DWORD error=GetLastError();Log("SurfaceUnlockRect",Find(s),static_cast<DWORD>(hr));SetLastError(error);return hr;}
using LockBufferFn=HRESULT(WINAPI*)(IDirect3DResource9*,UINT,UINT,void**,DWORD);static LockBufferFn realLockVertex,realLockIndex;
using UnlockBufferFn=HRESULT(WINAPI*)(IDirect3DResource9*);static UnlockBufferFn realUnlockVertex,realUnlockIndex;
static LockBufferFn realLockVertexHardware,realLockIndexHardware;
static UnlockBufferFn realUnlockVertexHardware,realUnlockIndexHardware;
static HRESULT BufferLock(LockBufferFn real,const char* api,IDirect3DResource9* s,UINT offset,UINT bytes,void** out,DWORD flags){MapScope scope(api,Find(s));HRESULT hr=real(s,offset,bytes,out,flags);DWORD error=GetLastError();MapRecord(api,Find(s),hr,SUCCEEDED(hr)&&out?*out:nullptr,bytes,flags);SetLastError(error);return hr;}
static HRESULT WINAPI LockVertex(IDirect3DResource9* s,UINT o,UINT b,void** p,DWORD f){return BufferLock(realLockVertex,"VertexLock",s,o,b,p,f);}
static HRESULT WINAPI LockIndex(IDirect3DResource9* s,UINT o,UINT b,void** p,DWORD f){return BufferLock(realLockIndex,"IndexLock",s,o,b,p,f);}
static HRESULT BufferUnlock(UnlockBufferFn real,const char* api,IDirect3DResource9* s){MapScope scope(api,Find(s));HRESULT hr=real(s);DWORD error=GetLastError();Log(api,Find(s),static_cast<DWORD>(hr));SetLastError(error);return hr;}
static HRESULT WINAPI UnlockVertex(IDirect3DResource9* s){return BufferUnlock(realUnlockVertex,"VertexUnlock",s);}
static HRESULT WINAPI UnlockIndex(IDirect3DResource9* s){return BufferUnlock(realUnlockIndex,"IndexUnlock",s);}
static HRESULT WINAPI LockVertexHardware(IDirect3DResource9* s,UINT o,UINT b,void** p,DWORD f){return BufferLock(realLockVertexHardware,"VertexLock",s,o,b,p,f);}
static HRESULT WINAPI LockIndexHardware(IDirect3DResource9* s,UINT o,UINT b,void** p,DWORD f){return BufferLock(realLockIndexHardware,"IndexLock",s,o,b,p,f);}
static HRESULT WINAPI UnlockVertexHardware(IDirect3DResource9* s){return BufferUnlock(realUnlockVertexHardware,"VertexUnlock",s);}
static HRESULT WINAPI UnlockIndexHardware(IDirect3DResource9* s){return BufferUnlock(realUnlockIndexHardware,"IndexUnlock",s);}
static LONG ChangeHooks(bool attach){std::vector<HANDLE> threads;HANDLE snapshot=CreateToolhelp32Snapshot(TH32CS_SNAPTHREAD,0);if(snapshot==INVALID_HANDLE_VALUE)return GetLastError();THREADENTRY32 entry{};entry.dwSize=sizeof(entry);BOOL more=Thread32First(snapshot,&entry);while(more){if(entry.th32OwnerProcessID==GetCurrentProcessId()&&entry.th32ThreadID!=GetCurrentThreadId()){HANDLE thread=OpenThread(THREAD_SUSPEND_RESUME|THREAD_GET_CONTEXT|THREAD_SET_CONTEXT|THREAD_QUERY_INFORMATION,FALSE,entry.th32ThreadID);if(thread)threads.push_back(thread);else if(GetLastError()!=ERROR_INVALID_PARAMETER){CloseHandle(snapshot);for(auto h:threads)CloseHandle(h);return GetLastError();}}more=Thread32Next(snapshot,&entry);}CloseHandle(snapshot);LONG error=DetourTransactionBegin();if(!error)error=DetourUpdateThread(GetCurrentThread());for(auto t:threads)if(!error)error=DetourUpdateThread(t);for(auto& h:hooks)if(!error)error=attach?DetourAttach(h.Target,h.Replacement):DetourDetach(h.Target,h.Replacement);if(error)DetourTransactionAbort();else error=DetourTransactionCommit();for(auto t:threads)CloseHandle(t);return error;}
extern "C" __declspec(dllexport) int __cdecl D3D9Start(const wchar_t* path){if(installed||!Start(path))return 1;try{MapPss::Configure();{Device9 seed(false);void** d=Table(seed.device);
    Set(realTexture,d[23],reinterpret_cast<void*>(Texture),"CreateTexture");Set(realVertex,d[26],reinterpret_cast<void*>(Vertex),"CreateVertexBuffer");Set(realIndex,d[27],reinterpret_cast<void*>(Index),"CreateIndexBuffer");Set(realTarget,d[28],reinterpret_cast<void*>(Target),"CreateRenderTarget");Set(realDepth,d[29],reinterpret_cast<void*>(Depth),"CreateDepthStencilSurface");Set(realPlain,d[36],reinterpret_cast<void*>(Plain),"CreateOffscreenPlainSurface");Set(realTargetEx,d[129],reinterpret_cast<void*>(TargetEx),"CreateRenderTargetEx");Set(realPlainEx,d[130],reinterpret_cast<void*>(PlainEx),"CreateOffscreenPlainSurfaceEx");Set(realDepthEx,d[131],reinterpret_cast<void*>(DepthEx),"CreateDepthStencilSurfaceEx");
    IDirect3DTexture9* texture=nullptr;IDirect3DSurface9* surface=nullptr;IDirect3DVertexBuffer9* vertex=nullptr;IDirect3DIndexBuffer9* index=nullptr;
    Need(SUCCEEDED(seed.device->CreateTexture(8,8,1,D3DUSAGE_DYNAMIC,D3DFMT_A8R8G8B8,D3DPOOL_DEFAULT,&texture,nullptr)));Need(SUCCEEDED(texture->GetSurfaceLevel(0,&surface)));Need(SUCCEEDED(seed.device->CreateVertexBuffer(4096,D3DUSAGE_DYNAMIC|D3DUSAGE_WRITEONLY,0,D3DPOOL_DEFAULT,&vertex,nullptr)));Need(SUCCEEDED(seed.device->CreateIndexBuffer(4096,D3DUSAGE_DYNAMIC|D3DUSAGE_WRITEONLY,D3DFMT_INDEX16,D3DPOOL_DEFAULT,&index,nullptr)));
    Set(realLevel,Table(texture)[18],reinterpret_cast<void*>(Level),"GetSurfaceLevel");Set(realLockTexture,Table(texture)[19],reinterpret_cast<void*>(LockTexture),"TextureLockRect");Set(realUnlockTexture,Table(texture)[20],reinterpret_cast<void*>(UnlockTexture),"TextureUnlockRect");Set(realLockSurface,Table(surface)[13],reinterpret_cast<void*>(LockSurface),"SurfaceLockRect");Set(realUnlockSurface,Table(surface)[14],reinterpret_cast<void*>(UnlockSurface),"SurfaceUnlockRect");Set(realLockVertex,Table(vertex)[11],reinterpret_cast<void*>(LockVertex),"VertexLock");Set(realUnlockVertex,Table(vertex)[12],reinterpret_cast<void*>(UnlockVertex),"VertexUnlock");Set(realLockIndex,Table(index)[11],reinterpret_cast<void*>(LockIndex),"IndexLock");Set(realUnlockIndex,Table(index)[12],reinterpret_cast<void*>(UnlockIndex),"IndexUnlock");
    IDirect3DSurface9* plain=nullptr;Need(SUCCEEDED(seed.device->CreateOffscreenPlainSurface(8,8,D3DFMT_A8R8G8B8,D3DPOOL_SYSTEMMEM,&plain,nullptr)));
    if(Table(plain)[13]!=reinterpret_cast<void*>(realLockSurface))Set(realLockPlain,Table(plain)[13],reinterpret_cast<void*>(LockPlain),"PlainSurfaceLockRect");
    if(Table(plain)[14]!=reinterpret_cast<void*>(realUnlockSurface))Set(realUnlockPlain,Table(plain)[14],reinterpret_cast<void*>(UnlockPlain),"PlainSurfaceUnlockRect");
    plain->Release();index->Release();vertex->Release();surface->Release();texture->Release();}
    {Device9 hardware(false,true);Need(Table(hardware.device)[26]==reinterpret_cast<void*>(realVertex)&&Table(hardware.device)[27]==reinterpret_cast<void*>(realIndex));
    IDirect3DVertexBuffer9* vertex=nullptr;IDirect3DIndexBuffer9* index=nullptr;
    Need(SUCCEEDED(hardware.device->CreateVertexBuffer(640032,D3DUSAGE_DYNAMIC|D3DUSAGE_WRITEONLY,0,D3DPOOL_DEFAULT,&vertex,nullptr)));Need(SUCCEEDED(hardware.device->CreateIndexBuffer(120006,D3DUSAGE_DYNAMIC|D3DUSAGE_WRITEONLY,D3DFMT_INDEX16,D3DPOOL_DEFAULT,&index,nullptr)));
    if(Table(vertex)[11]!=reinterpret_cast<void*>(realLockVertex))Set(realLockVertexHardware,Table(vertex)[11],reinterpret_cast<void*>(LockVertexHardware),"HardwareVertexLock");
    if(Table(vertex)[12]!=reinterpret_cast<void*>(realUnlockVertex))Set(realUnlockVertexHardware,Table(vertex)[12],reinterpret_cast<void*>(UnlockVertexHardware),"HardwareVertexUnlock");
    if(Table(index)[11]!=reinterpret_cast<void*>(realLockIndex))Set(realLockIndexHardware,Table(index)[11],reinterpret_cast<void*>(LockIndexHardware),"HardwareIndexLock");
    if(Table(index)[12]!=reinterpret_cast<void*>(realUnlockIndex))Set(realUnlockIndexHardware,Table(index)[12],reinterpret_cast<void*>(UnlockIndexHardware),"HardwareIndexUnlock");
    index->Release();vertex->Release();}
    // Distinct wrappers require distinct real implementations; never double-detour.
    for(size_t i=0;i<hooks.size();i++)for(size_t j=0;j<i;j++)Need(*hooks[i].Target!=*hooks[j].Target);
    for(auto& h:hooks)Log(h.Name,nullptr,reinterpret_cast<uintptr_t>(*h.Target),reinterpret_cast<uintptr_t>(h.Replacement));LONG code=ChangeHooks(true);Log("hooks-installed",nullptr,code,hooks.size());if(code)return code;installed=true;return 0;
    }catch(HRESULT hr){Log("observer-start-failure",nullptr,static_cast<DWORD>(hr));return 2;}}
extern "C" __declspec(dllexport) int __cdecl D3D9Mark(int value){MapPss::Mark(value);return errors;}
extern "C" __declspec(dllexport) int __cdecl D3D9Stop(){MapPss::Stop();if(installed){LONG code=ChangeHooks(false);Log("hooks-detached",nullptr,code);if(code)return code;installed=false;}Mark(999);LONG active=0;AcquireSRWLockShared(&gate);for(auto& item:items)if(!item->Closed)active++;ReleaseSRWLockShared(&gate);if(active){Log("close-deferred-for-live-private-owners",nullptr,active);FlushFileBuffers(output);return errors?1:0;}return Close()?0:1;}
