param(
    [Parameter(Mandatory)][ValidatePattern('^[A-Za-z0-9][A-Za-z0-9._-]*$')][string]$SnapshotId,
    [Parameter(Mandatory)][ValidatePattern('^[A-Za-z0-9][A-Za-z0-9._-]*$')][string]$ExperimentId
)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
function Require([bool]$Condition,[string]$Message){if(!$Condition){throw $Message}}
function Bytes-Hash([byte[]]$Bytes){[Convert]::ToHexString([Security.Cryptography.SHA256]::HashData($Bytes))}
function Range-Hash([byte[]]$Bytes,[int]$Offset,[int]$Count){$stream=[IO.MemoryStream]::new($Bytes,$Offset,$Count,$false);$algorithm=[Security.Cryptography.SHA256]::Create();try{[Convert]::ToHexString($algorithm.ComputeHash($stream))}finally{$algorithm.Dispose();$stream.Dispose()}}
$repositoryRoot=(& git -C $PSScriptRoot rev-parse --show-toplevel).Trim();$snapshotRoot=Join-Path $repositoryRoot "artifacts/performance/$SnapshotId";$experimentRoot=Join-Path $snapshotRoot $ExperimentId;$measurementPath=Join-Path $experimentRoot 'measurements.csv';$strictPath=Join-Path $snapshotRoot 'validation/resize-operation-boundary-strict-verification.json';$receiptPath=Join-Path $experimentRoot 'ledger-append.json';$ledgerPath=Join-Path $repositoryRoot 'docs/performance/OPTIMIZATION_MEASUREMENTS.csv'
Require(!(Test-Path $receiptPath))'Append receipt already exists.';$strict=Get-Content -Raw $strictPath|ConvertFrom-Json -DateKind String;Require($strict.Accepted -and $strict.Verdict-ceq 'ACCEPT_SAFETY_BOUNDARY' -and $strict.MeasurementRows-eq 105)'Strict acceptance differs.'
$manifest=@(Import-Csv (Join-Path $snapshotRoot 'manifest.csv'));$appender=@($manifest|Where-Object Path -CEQ 'scripts/performance/Append-ResizeOperationSnapshotBoundaryMeasurements.ps1');Require($appender.Count-eq 1 -and $appender[0].SHA256-ceq(Get-FileHash -Algorithm SHA256 $PSCommandPath).Hash)'Frozen appender differs.'
$bytes=[IO.File]::ReadAllBytes($measurementPath);Require((Bytes-Hash $bytes)-ceq $strict.MeasurementsSHA256)'Measurements changed after strict verification.';$encoding=[Text.UTF8Encoding]::new($false,$true);$text=$encoding.GetString($bytes).TrimStart([char]0xFEFF);$rows=@($text|ConvertFrom-Csv);Require($rows.Count-eq 105 -and @($rows|Where-Object{$_.experiment_id-cne $ExperimentId -or $_.snapshot_id-cne $SnapshotId -or $_.perf_id-cne 'PERF-022'}).Count-eq 0)'Measurement rows differ.'
$headerEnd=[Array]::IndexOf($bytes,[byte]10);Require($headerEnd-ge 0 -and $bytes[-1]-eq 10)'Measurement CSV is not newline terminated.';$suffix=[byte[]]$bytes[($headerEnd+1)..($bytes.Length-1)];Require(@($suffix|Where-Object{$_-eq 10}).Count-eq 105)'Suffix count differs.'
$expectedLength=41550390L;$expectedHash='12AC0C1FE5B2A182DD6C89EB863C90FD5EA246C690C28EAAE349F1467DF12C57';$expectedLines=41011;$expectedRows=41010
$stream=[IO.File]::Open($ledgerPath,[IO.FileMode]::Open,[IO.FileAccess]::ReadWrite,[IO.FileShare]::None);try{Require($stream.Length-eq $expectedLength)'Ledger length differs from exact prefix.';$prefix=[byte[]]::new([int]$expectedLength);$stream.ReadExactly($prefix,0,$prefix.Length);Require((Bytes-Hash $prefix)-ceq $expectedHash -and $prefix[-1]-eq 10)'Ledger prefix differs.';$prefixText=$encoding.GetString($prefix).TrimStart([char]0xFEFF);Require($prefixText.Split([char]10).Length-1-eq $expectedLines -and !$prefixText.Contains('"'+$ExperimentId+'"'))'Ledger rows differ or experiment exists.';$ledgerHeader=$prefixText.Substring(0,$prefixText.IndexOf([char]10)).TrimEnd([char]13);$measurementHeader=$text.Substring(0,$text.IndexOf([char]10)).TrimEnd([char]13);Require($ledgerHeader-ceq $measurementHeader)'Ledger schema differs.';$stream.Write($suffix,0,$suffix.Length);$stream.Flush($true);$newLength=$stream.Length;$stream.Position=0;$newBytes=[byte[]]::new([int]$newLength);$stream.ReadExactly($newBytes,0,$newBytes.Length);$newHash=Bytes-Hash $newBytes;Require((Range-Hash $newBytes 0 $prefix.Length)-ceq $expectedHash -and (Range-Hash $newBytes $prefix.Length $suffix.Length)-ceq(Bytes-Hash $suffix))'Append readback differs.'}finally{$stream.Dispose()}
$receipt=[ordered]@{Verdict='ACCEPT';SnapshotId=$SnapshotId;ExperimentId=$ExperimentId;PerfId='PERF-022';OldLength=$expectedLength;OldSHA256=$expectedHash;OldLines=$expectedLines;OldRows=$expectedRows;NewLength=$newLength;NewSHA256=$newHash;NewLines=$expectedLines+105;NewRows=$expectedRows+105;PrefixLength=$expectedLength;PrefixSHA256=$expectedHash;SuffixLength=$suffix.Length;SuffixSHA256=Bytes-Hash $suffix;AppendedRows=105;MeasurementsSHA256=Bytes-Hash $bytes;StrictReportSHA256=(Get-FileHash -Algorithm SHA256 $strictPath).Hash;AppenderSHA256=(Get-FileHash -Algorithm SHA256 $PSCommandPath).Hash};$json=$receipt|ConvertTo-Json -Depth 4;$file=[IO.File]::Open($receiptPath,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::None);try{$receiptBytes=$encoding.GetBytes($json+[Environment]::NewLine);$file.Write($receiptBytes,0,$receiptBytes.Length)}finally{$file.Dispose()};$json
