param(
    [Parameter(Mandatory)][ValidatePattern('^[A-Za-z0-9][A-Za-z0-9._-]*$')][string]$SnapshotId,
    [ValidateSet(0,3)][int]$ExpectedFailed = 0
)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
function Require([bool]$Condition,[string]$Message){if(!$Condition){throw $Message}}
function Hash([string]$Path){(Get-FileHash -Algorithm SHA256 -LiteralPath $Path).Hash}
$repositoryRoot=(& git -C $PSScriptRoot rev-parse --show-toplevel).Trim();Require($LASTEXITCODE-eq 0 -and [StringComparer]::OrdinalIgnoreCase.Equals([IO.Path]::GetFullPath((Get-Location).Path),[IO.Path]::GetFullPath($repositoryRoot)))'Run from repository root.';$snapshotRoot=Join-Path $repositoryRoot "artifacts/performance/$SnapshotId";Require(!(Test-Path $snapshotRoot))'Snapshot already exists.'
& (Join-Path $PSScriptRoot 'Save-ImplementationSnapshot.ps1') -SnapshotId $SnapshotId|Out-Null;$validationRoot=Join-Path $snapshotRoot 'validation';$binaryRoot=Join-Path $snapshotRoot 'release-test-binaries';New-Item -ItemType Directory -Path $validationRoot,$binaryRoot|Out-Null
$log=Join-Path $validationRoot 'Release-provider-snapshot.log';& dotnet test FancyWM.Tests/FancyWM.Tests.csproj --configuration Release --no-restore --filter 'FullyQualifiedName~Win32DisplayManagerSnapshotTest' --logger 'trx;LogFileName=Release-provider-snapshot.trx' --results-directory $validationRoot *> $log;$exit=$LASTEXITCODE
[xml]$trx=Get-Content -Raw (Join-Path $validationRoot 'Release-provider-snapshot.trx');$all=@($trx.SelectNodes("//*[local-name()='UnitTestResult']"));$leaves=@($all|Where-Object{$_.SelectNodes("./*[local-name()='InnerResults']/*[local-name()='UnitTestResult']").Count-eq 0});$failed=@($leaves|Where-Object outcome -CNE 'Passed');Require($leaves.Count-eq 9 -and $failed.Count-eq $ExpectedFailed -and (($ExpectedFailed-eq 0)-eq($exit-eq 0)))'Fixture outcome differs.'
$outputRoot=Join-Path $repositoryRoot 'FancyWM.Tests/bin/Release/net10.0-windows10.0.18362.0';Copy-Item -Path (Join-Path $outputRoot '*') -Destination $binaryRoot -Recurse;$archive=@(Get-ChildItem -LiteralPath $binaryRoot -Recurse -File|Sort-Object FullName|ForEach-Object{[pscustomobject]@{Path=[IO.Path]::GetRelativePath($binaryRoot,$_.FullName).Replace('\','/');Length=$_.Length;SHA256=Hash $_.FullName}});$archive|Export-Csv -NoTypeInformation (Join-Path $snapshotRoot 'release-test-binaries.csv')
$summary=[ordered]@{Verdict=if($ExpectedFailed-eq 0){'CANDIDATE_PASS'}else{'BASELINE_RED'};SnapshotId=$SnapshotId;Total=$leaves.Count;Passed=$leaves.Count-$failed.Count;Failed=$failed.Count;RawResults=$all.Count;ExpectedFailed=$ExpectedFailed;WinManWindowsDllSHA256=@($archive|Where-Object Path -CEQ 'WinMan.Windows.dll')[0].SHA256;FancyWMTestsDllSHA256=@($archive|Where-Object Path -CEQ 'FancyWM.Tests.dll')[0].SHA256;CreatedUtc=[DateTimeOffset]::UtcNow.ToString('o')};$summary|ConvertTo-Json -Depth 4|Set-Content (Join-Path $validationRoot 'fixture-summary.json');$summary|ConvertTo-Json -Depth 4
