param(
    [Parameter(Mandatory)][ValidatePattern('^[A-Za-z0-9][A-Za-z0-9._-]*$')][string]$BaselineSnapshotId,
    [Parameter(Mandatory)][ValidatePattern('^[A-Za-z0-9][A-Za-z0-9._-]*$')][string]$CandidateSnapshotId,
    [Parameter(Mandatory)][ValidatePattern('^[A-Za-z0-9][A-Za-z0-9._-]*$')][string]$ExperimentId
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest
function Require([bool]$Condition,[string]$Message){if(!$Condition){throw $Message}}
function Hash([string]$Path){(Get-FileHash -Algorithm SHA256 -LiteralPath $Path).Hash}
function Load-Json([string]$Path){Get-Content -Raw -LiteralPath $Path|ConvertFrom-Json -DateKind String}

$repositoryRoot=(& git -C $PSScriptRoot rev-parse --show-toplevel).Trim()
Require($LASTEXITCODE-eq 0) 'Cannot resolve repository root.'
$baselineRoot=Join-Path $repositoryRoot "artifacts/performance/$BaselineSnapshotId"
$candidateRoot=Join-Path $repositoryRoot "artifacts/performance/$CandidateSnapshotId"
$experimentRoot=Join-Path $candidateRoot $ExperimentId
$outputRoot=Join-Path $candidateRoot 'validation'
$outputPath=Join-Path $outputRoot 'focus-concurrent-strict-verification.json'
Require(!(Test-Path $outputPath)) 'Immutable strict report already exists.'
foreach($path in @($baselineRoot,$candidateRoot,$experimentRoot)){Require(Test-Path $path) "Evidence root missing: $path"}
$baselineManifest=@(Import-Csv (Join-Path $baselineRoot 'manifest.csv'));$candidateManifest=@(Import-Csv (Join-Path $candidateRoot 'manifest.csv'))
Require($baselineManifest.Count-eq $candidateManifest.Count) 'Manifest counts differ.'
$differences=[Collections.Generic.List[string]]::new()
foreach($record in $candidateManifest){$old=@($baselineManifest|Where-Object Path -CEQ $record.Path);Require($old.Count-eq 1) "Baseline path missing: $($record.Path)";foreach($entry in @([pscustomobject]@{Root=$candidateRoot;Record=$record},[pscustomobject]@{Root=$baselineRoot;Record=$old[0]})){Require((Hash (Join-Path $entry.Root "source/$($entry.Record.Path)"))-ceq $entry.Record.SHA256) "Frozen source changed: $($entry.Record.Path)"};if($old[0].SHA256-cne $record.SHA256){$differences.Add($record.Path)}}
Require(($differences-join '|')-ceq 'FancyWM/Utilities/FocusHelper.cs') 'Source delta is not exactly FocusHelper.cs.'
$baselinePrepared=Load-Json (Join-Path $baselineRoot 'release-test-binaries.provenance.json');$candidatePrepared=Load-Json (Join-Path $candidateRoot 'release-test-binaries.provenance.json')
Require($baselinePrepared.Role-ceq 'Baseline' -and $candidatePrepared.Role-ceq 'Candidate' -and $baselinePrepared.Regression.Passed-eq 5 -and $baselinePrepared.Regression.Failed-eq 3 -and $candidatePrepared.Regression.Passed-eq 8 -and $candidatePrepared.Regression.Failed-eq 0) 'Prepared regression evidence differs.'
Require($baselinePrepared.FixtureSourceSHA256-ceq $candidatePrepared.FixtureSourceSHA256 -and $baselinePrepared.FancyWMDllSHA256-cne $candidatePrepared.FancyWMDllSHA256) 'Common fixture source/distinct production binary proof failed.'
$runner=@($candidateManifest|Where-Object Path -CEQ 'scripts/performance/Measure-FocusConcurrentAdmission.ps1');$verifier=@($candidateManifest|Where-Object Path -CEQ 'scripts/performance/Verify-FocusConcurrentAdmission.ps1')
Require($runner.Count-eq 1 -and $verifier.Count-eq 1 -and (Hash (Join-Path $candidateRoot "source/$($runner[0].Path)"))-ceq $runner[0].SHA256 -and (Hash $PSCommandPath)-ceq $verifier[0].SHA256) 'Frozen runner/verifier differs.'
$provenancePath=Join-Path $experimentRoot 'measurement-provenance.json';$measurementsPath=Join-Path $experimentRoot 'measurements.csv';$rawPath=Join-Path $experimentRoot 'raw-counters.csv';$processPath=Join-Path $experimentRoot 'process-times.csv';$pairedPath=Join-Path $experimentRoot 'paired-results.csv'
foreach($path in @($provenancePath,$measurementsPath,$rawPath,$processPath,$pairedPath)){Require(Test-Path $path) "Measurement evidence missing: $path"}
$provenance=Load-Json $provenancePath
Require($provenance.ExperimentId-ceq $ExperimentId -and $provenance.BaselineSnapshotId-ceq $BaselineSnapshotId -and $provenance.CandidateSnapshotId-ceq $CandidateSnapshotId -and $provenance.MeasurementRows-eq 1090 -and $provenance.RawCounters-eq 1090 -and $provenance.ProcessCount-eq 10 -and $provenance.AllocationPairsImproved-eq 15 -and $provenance.SemanticComparisons-eq 400) 'Measurement provenance dimensions differ.'
$rows=@(Import-Csv $measurementsPath);$raw=@(Import-Csv $rawPath);$processes=@(Import-Csv $processPath);$paired=@(Import-Csv $pairedPath)
Require($rows.Count-eq 1090 -and $raw.Count-eq 1090 -and $processes.Count-eq 10 -and $paired.Count-eq 20) 'Evidence CSV dimensions differ.'
$schema='experiment_id|snapshot_id|scenario|configuration|window_count|metric|unit|run|value|iterations|instrument|perf_id|variant|pair|binary_sha256|benchmark_sha256'
$values=[Collections.Generic.Dictionary[string,long]]::new([StringComparer]::Ordinal);$keys=[Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal)
foreach($row in $rows){Require(($row.PSObject.Properties.Name-join '|')-ceq $schema -and $row.experiment_id-ceq $ExperimentId -and $row.perf_id-ceq 'PERF-030' -and $row.variant-cin @('baseline','candidate') -and $row.run-cmatch '^[1-5]$' -and $row.pair-ceq $row.run -and $row.scenario-cmatch '^Actual FocusHelper\.RequestSequence\.Enqueue/RunWorker; (?<scenario>focus-(?:first-worker-delegate|concurrent-enqueue|worker-overlap-(?:direct-success|alt-retry|attach-failure))); controlled overlap$' -and $row.value-cmatch '^(0|[1-9][0-9]*)$') 'Malformed measurement row.';$scenario=[regex]::Match($row.scenario,'; (?<scenario>focus-[^;]+);').Groups['scenario'].Value;$key="$($row.variant)/$($row.run)/$scenario/$($row.metric)";$value=[long]::Parse($row.value,[Globalization.CultureInfo]::InvariantCulture);Require($keys.Add($key)-and $values.TryAdd($key,$value)) "Duplicate measurement row: $key";$expectedSnapshot=if($row.variant-ceq 'baseline'){$BaselineSnapshotId}else{$CandidateSnapshotId};$expectedBinary=if($row.variant-ceq 'baseline'){$baselinePrepared.FancyWMDllSHA256}else{$candidatePrepared.FancyWMDllSHA256};Require($row.snapshot_id-ceq $expectedSnapshot -and $row.binary_sha256-ceq $expectedBinary -and $row.benchmark_sha256-ceq $candidatePrepared.FancyWMTestsDllSHA256) 'Row binary provenance differs.'}
$expectedOrder='baseline-1|candidate-1|candidate-2|baseline-2|baseline-3|candidate-3|candidate-4|baseline-4|baseline-5|candidate-5'
Require(($processes.RunId-join '|')-ceq $expectedOrder) 'Process order differs.'
for($i=0;$i-lt $processes.Count;$i++){if($i){Require([DateTimeOffset]::Parse($processes[$i].Start)-ge [DateTimeOffset]::Parse($processes[$i-1].Finish)) 'Process intervals overlap.'};$run=$processes[$i].RunId;foreach($suffix in @('trx','stdout.log','stderr.log')){$field=if($suffix-ceq 'trx'){'TrxSHA256'}elseif($suffix-ceq 'stdout.log'){'StdOutSHA256'}else{'StdErrSHA256'};Require((Hash (Join-Path $experimentRoot "$run.$suffix"))-ceq $processes[$i].$field) "Process artifact differs: $run/$suffix"}}
$semanticMetrics=@('admissions','worker-starts','worker-exits','calls','accepted','replaced','true-results','false-results','background-workers','overlapped-callers','queue-calls','attach-calls','detach-calls','focus-calls','owned-attachments','superseded','completion-callbacks','completion-order-checksum','latest-current','worker-thread-count','thread-id-reads','foreground-id-reads','alt-presses','native-timeouts')
$scenarios=@('focus-first-worker-delegate','focus-concurrent-enqueue','focus-worker-overlap-direct-success','focus-worker-overlap-alt-retry','focus-worker-overlap-attach-failure')
$semanticComparisons=0;$allocation=[Collections.Generic.List[object]]::new();$timingWins=0;$timingLosses=0;$timingTies=0
foreach($scenario in $scenarios){foreach($pair in 1..5){foreach($metric in $semanticMetrics){$bk="baseline/$pair/$scenario/$metric";$ck="candidate/$pair/$scenario/$metric";if($values.ContainsKey($bk)){Require($values.ContainsKey($ck)-and $values[$bk]-eq $values[$ck]) "Semantic mismatch: $pair/$scenario/$metric";$semanticComparisons++}};if($scenario-clike 'focus-worker-overlap-*'){$b=$values["baseline/$pair/$scenario/worker-transition-allocated-bytes"];$c=$values["candidate/$pair/$scenario/worker-transition-allocated-bytes"];Require($b-eq 24624 -and $c-lt $b -and $c-le 8160) "Worker transition allocation gate failed: $pair/$scenario ($b -> $c)";$allocation.Add([pscustomobject]@{Scenario=$scenario;Pair=$pair;BaselineBytes=$b;CandidateBytes=$c;SavedBytes=$b-$c;Transitions=255})};if($values.ContainsKey("baseline/$pair/$scenario/enqueue-elapsed-ticks")){$b=$values["baseline/$pair/$scenario/enqueue-elapsed-ticks"];$c=$values["candidate/$pair/$scenario/enqueue-elapsed-ticks"];if($c-lt $b){$timingWins++}elseif($c-gt $b){$timingLosses++}else{$timingTies++}}}}
Require($semanticComparisons-eq 400 -and $allocation.Count-eq 15) 'Strict comparison counts differ.'
foreach($pair in 1..5){foreach($metric in @('first-caller-allocated-bytes','warm-caller-allocated-bytes','lazy-delegate-bytes')){$b=$values["baseline/$pair/focus-first-worker-delegate/$metric"];$c=$values["candidate/$pair/focus-first-worker-delegate/$metric"];$expected=if($metric-ceq 'first-caller-allocated-bytes'){368}elseif($metric-ceq 'warm-caller-allocated-bytes'){304}else{64};Require($b-eq $expected -and $c-eq $expected) "First lazy delegate evidence differs: $pair/$metric"}}
$report=[ordered]@{Verdict='ACCEPT';Accepted=$true;Scenario='FocusConcurrentAdmission';PerfId='PERF-030';BaselineSnapshot=$BaselineSnapshotId;CandidateSnapshot=$CandidateSnapshotId;ExperimentId=$ExperimentId;SourceManifestDifferences=@($differences);BinaryDifferences=@('FancyWM.dll');BaselineProductionSHA256=$baselinePrepared.FancyWMDllSHA256;CandidateProductionSHA256=$candidatePrepared.FancyWMDllSHA256;CommonFixtureSHA256=$candidatePrepared.FancyWMTestsDllSHA256;BaselineRegressionLeaves=8;BaselineSemanticTestsPassed=5;BaselineAllocationTestsFailed=3;CandidateRegressionLeaves=8;CandidateRegressionPassed=8;ProcessCount=10;ProcessOrder=$processes.RunId;MeasurementRows=$rows.Count;RawCounters=$raw.Count;SemanticComparisons=$semanticComparisons;AllocationPairs=$allocation.Count;Allocation=@($allocation);TimingWins=$timingWins;TimingLosses=$timingLosses;TimingTies=$timingTies;TimingAcceptanceGate=$false;MeasurementsSHA256=Hash $measurementsPath;RawCountersSHA256=Hash $rawPath;ProcessTimesSHA256=Hash $processPath;PairedResultsSHA256=Hash $pairedPath;MeasurementProvenanceSHA256=Hash $provenancePath;BaselineManifestSHA256=Hash(Join-Path $baselineRoot 'manifest.csv');CandidateManifestSHA256=Hash(Join-Path $candidateRoot 'manifest.csv');VerifierSHA256=Hash $PSCommandPath;RunnerSHA256=$runner[0].SHA256;AllocationScope=$provenance.AllocationScope;TimingScope=$provenance.TimingScope;NotMeasured=$provenance.NotMeasured}
New-Item -ItemType Directory -Force -Path $outputRoot|Out-Null
$report|ConvertTo-Json -Depth 8|Set-Content -LiteralPath $outputPath
$report|ConvertTo-Json -Depth 8
