param(
    [Parameter(Mandatory)][ValidatePattern('^[A-Za-z0-9][A-Za-z0-9._-]*$')][string]$SnapshotId,
    [Parameter(Mandatory)][ValidatePattern('^[A-Za-z0-9][A-Za-z0-9._-]*$')][string]$BaselineSnapshotId,
    [Parameter(Mandatory)][ValidatePattern('^[A-Za-z0-9][A-Za-z0-9._-]*$')][string]$CandidateSnapshotId,
    [Parameter(Mandatory)][ValidatePattern('^[A-Za-z0-9][A-Za-z0-9._-]*$')][string]$ExperimentId,
    [Parameter(Mandatory)][ValidatePattern('^[A-Za-z0-9][A-Za-z0-9._-]*$')][string]$DependencySnapshotId
)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
function Require([bool]$Condition,[string]$Message){if(!$Condition){throw $Message}}
function Hash([string]$Path){(Get-FileHash -Algorithm SHA256 -LiteralPath $Path).Hash}
function Load-Json([string]$Path){Get-Content -Raw -LiteralPath $Path|ConvertFrom-Json -DateKind String}
function Trx-Stats([string]$Path){
 $settings=[Xml.XmlReaderSettings]::new();$settings.DtdProcessing=[Xml.DtdProcessing]::Prohibit;$settings.XmlResolver=$null;$reader=[Xml.XmlReader]::Create($Path,$settings)
 try{$doc=[Xml.XmlDocument]::new();$doc.XmlResolver=$null;$doc.Load($reader)}finally{$reader.Dispose()}
 $all=@($doc.SelectNodes('//*[local-name()="UnitTestResult"]'));$leaves=@($all|Where-Object{$_.SelectNodes('./*[local-name()="InnerResults"]/*[local-name()="UnitTestResult"]').Count-eq 0});$failed=@($leaves|Where-Object outcome -CNE 'Passed')
 [pscustomobject]@{Raw=$all.Count;Leaves=$leaves.Count;Passed=@($leaves|Where-Object outcome -CEQ 'Passed').Count;Failed=$failed.Count;Names=@($leaves.testName|Sort-Object);SHA256=Hash $Path}
}
function Verify-Snapshot([string]$Root,[string]$Id){
 $snapshotPath=Join-Path $Root 'snapshot.json';$manifestPath=Join-Path $Root 'manifest.csv';$snapshot=Load-Json $snapshotPath;$manifest=@(Import-Csv $manifestPath);Require($snapshot.SnapshotId-ceq $Id -and $snapshot.ManifestSHA256-ceq (Hash $manifestPath)) "Snapshot identity differs: $Id";$seen=[Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal)
 foreach($record in $manifest){Require($seen.Add($record.Path)-and $record.SHA256-cmatch '^[0-9A-F]{64}$' -and (Hash (Join-Path $Root "source/$($record.Path)"))-ceq $record.SHA256) "Frozen source differs: $Id/$($record.Path)"}
 [pscustomobject]@{Snapshot=$snapshot;Manifest=$manifest;ManifestSHA256=Hash $manifestPath;SnapshotSHA256=Hash $snapshotPath}
}
function Compare-Manifests($Left,$Right){$changes=[Collections.Generic.List[string]]::new();$paths=@($Left.Path+$Right.Path|Sort-Object -Unique);foreach($path in $paths){$l=@($Left|Where-Object Path -CEQ $path);$r=@($Right|Where-Object Path -CEQ $path);if($l.Count-ne 1 -or $r.Count-ne 1 -or $l[0].SHA256-cne $r[0].SHA256){$changes.Add($path)}};@($changes)}

$repositoryRoot=(& git -C $PSScriptRoot rev-parse --show-toplevel).Trim();Require($LASTEXITCODE-eq 0) 'Cannot resolve repository root.'
$head=(& git -C $repositoryRoot rev-parse HEAD).Trim();$tree=(& git -C $repositoryRoot rev-parse 'HEAD^{tree}').Trim();Require($head-ceq '4fb943be3ee3768bb6de42b16b0a22bdbafa2e0b' -and $tree-ceq '48c574b1abd3adb858942bd8c6a0f4d9fb3e39b7') 'HEAD/tree differs.'
$baselineRoot=Join-Path $repositoryRoot "artifacts/performance/$BaselineSnapshotId";$candidateRoot=Join-Path $repositoryRoot "artifacts/performance/$CandidateSnapshotId";$c2Root=Join-Path $repositoryRoot "artifacts/performance/$SnapshotId";$validationRoot=Join-Path $c2Root 'validation';$experimentRoot=Join-Path $candidateRoot $ExperimentId
$baseline=Verify-Snapshot $baselineRoot $BaselineSnapshotId;$candidate=Verify-Snapshot $candidateRoot $CandidateSnapshotId;$c2=Verify-Snapshot $c2Root $SnapshotId
Require($c2.Snapshot.Commit-ceq $head -and $c2.Snapshot.Tree-ceq $tree) 'C2 baseline identity differs.'
$r0c1=Compare-Manifests $baseline.Manifest $candidate.Manifest;$c1c2=Compare-Manifests $candidate.Manifest $c2.Manifest
Require(($r0c1-join '|')-ceq 'FancyWM/Utilities/FocusHelper.cs') 'R0/C1 delta differs.'
Require(($c1c2-join '|')-ceq 'docs/performance/OPTIMIZATION_MEASUREMENTS.csv|scripts/performance/Verify-FocusConcurrentDelivery.ps1') "C1/C2 protocol delta differs: $($c1c2-join '|')"
$writer=@($c2.Manifest|Where-Object Path -CEQ 'scripts/performance/Verify-FocusConcurrentDelivery.ps1');Require($writer.Count-eq 1 -and $writer[0].SHA256-ceq (Hash $PSCommandPath)) 'Delivery verifier differs from frozen C2 source.'
foreach($name in @('TODO.md','IMPLEMENTATION_STATUS.md')){$expected=if($name-ceq 'TODO.md'){'C5AE4822AC1B62A92E66FE4C282035CD441F096CD93358DCE2E79119972C61D1'}else{'580E05F35A0D6EEE150B175E7886FC87F2B2FAB76025B498BC656A7E9830335D'};Require((Hash (Join-Path $repositoryRoot $name))-ceq $expected -and (Hash (Join-Path $c2Root "source/$name"))-ceq $expected) "Functional document changed: $name"}

$receiptPath=Join-Path $validationRoot 'run-receipt.json';$receipt=Load-Json $receiptPath;Require($receipt.SnapshotId-ceq $SnapshotId -and $receipt.ExitCode-eq 0 -and [DateTimeOffset]::Parse($receipt.StartedUtc)-lt [DateTimeOffset]::Parse($receipt.FinishedUtc)) 'Full-gate receipt differs.'
$fullTests=[Collections.Generic.List[object]]::new();foreach($configuration in @('Debug','Release')){foreach($suite in @('FancyWM.Tests','FancyWM.Layouts.Tests','FancyWM.ThemeEngine.Tests')){$path=Join-Path $validationRoot "$configuration-$suite.trx";$stats=Trx-Stats $path;$expectedLeaves=if($suite-ceq 'FancyWM.Tests'){if($configuration-ceq 'Debug'){2012}else{2068}}elseif($suite-ceq 'FancyWM.Layouts.Tests'){160}else{31};Require($stats.Leaves-eq $expectedLeaves -and $stats.Passed-eq $expectedLeaves -and $stats.Failed-eq 0) "Full test count differs: $configuration/$suite";$fullTests.Add([pscustomobject]@{Configuration=$configuration;Suite=$suite;Raw=$stats.Raw;Leaves=$stats.Leaves;Passed=$stats.Passed;Failed=$stats.Failed;TrxSHA256=$stats.SHA256;LogSHA256=Hash(Join-Path $validationRoot "$configuration-$suite.log")})};foreach($kind in @('restore','gui','full')){$log=Join-Path $validationRoot "$configuration-$kind.log";Require((Get-Item $log).Length-gt 0) "Build log missing/empty: $configuration/$kind"}}

$candidateTests=[Collections.Generic.List[object]]::new();foreach($configuration in @('Debug','Release')){foreach($scope in @('targeted','affected')){$path=Join-Path $candidateRoot "validation/$configuration-focus-concurrent-$scope.trx";$stats=Trx-Stats $path;$expectedLeaves=if($scope-ceq 'targeted'){8}else{247};Require($stats.Leaves-eq $expectedLeaves -and $stats.Passed-eq $expectedLeaves -and $stats.Failed-eq 0) "Candidate test count differs: $configuration/$scope";$candidateTests.Add([pscustomobject]@{Configuration=$configuration;Scope=$scope;Raw=$stats.Raw;Leaves=$stats.Leaves;Passed=$stats.Passed;Failed=$stats.Failed;TrxSHA256=$stats.SHA256;LogSHA256=Hash([IO.Path]::ChangeExtension($path,'.log'))})}}

$strictPath=Join-Path $candidateRoot 'validation/focus-concurrent-strict-verification.json';$strict=Load-Json $strictPath;Require($strict.Accepted -is [bool] -and $strict.Accepted -and $strict.Verdict-ceq 'ACCEPT' -and $strict.BaselineSnapshot-ceq $BaselineSnapshotId -and $strict.CandidateSnapshot-ceq $CandidateSnapshotId -and $strict.ExperimentId-ceq $ExperimentId -and $strict.MeasurementRows-eq 1090 -and $strict.SemanticComparisons-eq 400 -and $strict.AllocationPairs-eq 15) 'C1 strict evidence differs.'
$measurementsPath=Join-Path $experimentRoot 'measurements.csv';Require((Hash $measurementsPath)-ceq $strict.MeasurementsSHA256) 'Measurements hash differs.';$rows=@(Import-Csv $measurementsPath);Require($rows.Count-eq 1090) 'Measurement row count differs.'
$values=[Collections.Generic.Dictionary[string,long]]::new([StringComparer]::Ordinal);foreach($row in $rows){$scenario=[regex]::Match($row.scenario,'; (?<scenario>focus-[^;]+);').Groups['scenario'].Value;$key="$($row.variant)/$($row.run)/$scenario/$($row.metric)";Require($values.TryAdd($key,[long]::Parse($row.value,[Globalization.CultureInfo]::InvariantCulture))) "Duplicate measurement row: $key"}
$allocationPairs=0;foreach($scenario in @('focus-worker-overlap-direct-success','focus-worker-overlap-alt-retry','focus-worker-overlap-attach-failure')){foreach($pair in 1..5){$b=$values["baseline/$pair/$scenario/worker-transition-allocated-bytes"];$c=$values["candidate/$pair/$scenario/worker-transition-allocated-bytes"];Require($b-eq 24624 -and $c-eq 144) "Fresh worker allocation check differs: $pair/$scenario";$allocationPairs++}}
$semanticMetrics=@('admissions','worker-starts','worker-exits','calls','accepted','replaced','true-results','false-results','background-workers','overlapped-callers','queue-calls','attach-calls','detach-calls','focus-calls','owned-attachments','superseded','completion-callbacks','completion-order-checksum','latest-current','worker-thread-count','thread-id-reads','foreground-id-reads','alt-presses','native-timeouts');$semanticComparisons=0
foreach($scenario in @('focus-first-worker-delegate','focus-concurrent-enqueue','focus-worker-overlap-direct-success','focus-worker-overlap-alt-retry','focus-worker-overlap-attach-failure')){foreach($pair in 1..5){foreach($metric in $semanticMetrics){$bk="baseline/$pair/$scenario/$metric";$ck="candidate/$pair/$scenario/$metric";if($values.ContainsKey($bk)){Require($values.ContainsKey($ck)-and $values[$bk]-eq $values[$ck]) "Fresh semantic check differs: $pair/$scenario/$metric";$semanticComparisons++}}}}
Require($allocationPairs-eq 15 -and $semanticComparisons-eq 400) 'Fresh measurement comparison totals differ.'
$reverificationPath=Join-Path $validationRoot 'focus-concurrent-measurement-reverification.json';$summaryPath=Join-Path $validationRoot 'validation-summary.json';Require(!(Test-Path $reverificationPath)-and !(Test-Path $summaryPath)) 'Immutable delivery outputs already exist.'
$reverification=[ordered]@{Verdict='ACCEPT';ExperimentId=$ExperimentId;MeasurementsSHA256=Hash $measurementsPath;Rows=$rows.Count;AllocationPairs=$allocationPairs;BaselineWorkerTransitionBytes=24624;CandidateWorkerTransitionBytes=144;TransitionsPerScenario=255;SemanticComparisons=$semanticComparisons;StrictReportSHA256=Hash $strictPath;ReverifiedUtc=[DateTimeOffset]::UtcNow.ToString('o')};$reverification|ConvertTo-Json -Depth 5|Set-Content $reverificationPath

$appendPath=Join-Path $experimentRoot 'ledger-append.json';$append=Load-Json $appendPath;Require($append.Verdict-ceq 'ACCEPT' -and $append.OldLength-eq 39811448 -and $append.OldSHA256-ceq '9D40BD0AE06DE654DBE0C9E0CE036E55B0463A892621DCA23A873CA3D3D1B0B1' -and $append.NewLength-eq 40597252 -and $append.NewSHA256-ceq '4EB8974ADA760ADB195853E1C2CABBE4C9F687BF13681D88BD226E3F890F837A' -and $append.AppendedRows-eq 1090) 'Ledger append proof differs.'
$ledgerPath=Join-Path $repositoryRoot 'docs/performance/OPTIMIZATION_MEASUREMENTS.csv';Require((Get-Item $ledgerPath).Length-eq $append.NewLength -and (Hash $ledgerPath)-ceq $append.NewSHA256 -and (Hash (Join-Path $c2Root 'source/docs/performance/OPTIMIZATION_MEASUREMENTS.csv'))-ceq $append.NewSHA256) 'Current/frozen C2 ledger differs.'

$dependencyRoot=Join-Path $repositoryRoot "artifacts/performance/$DependencySnapshotId/dependency-check";foreach($path in @('build.log','binary.csv','conflict.log','winman.zip','winman-windows.zip')){Require(Test-Path (Join-Path $dependencyRoot $path)) "Dependency evidence missing: $path"};$dependencyBinary=@(Import-Csv (Join-Path $dependencyRoot 'binary.csv'));Require($dependencyBinary.Count-eq 1 -and $dependencyBinary[0].Hash-cmatch '^[0-9A-F]{64}$') 'Dependency binary evidence differs.'
$dependencyEvidence=@(Get-ChildItem -LiteralPath $dependencyRoot -File|Sort-Object Name|ForEach-Object{[pscustomobject]@{Path=$_.Name;Bytes=$_.Length;SHA256=Hash $_.FullName}})

$packageProvenancePath=Join-Path $c2Root 'release/provenance.json';$packageProvenance=Load-Json $packageProvenancePath;$packagePath=Join-Path $c2Root $packageProvenance.Path;$sourcePackagePath=Join-Path $repositoryRoot $packageProvenance.Source
Require($packageProvenance.Installed -is [bool] -and !$packageProvenance.Installed -and !$packageProvenance.Launched -and !$packageProvenance.Published -and (Hash $packagePath)-ceq $packageProvenance.SHA256 -and (Hash $sourcePackagePath)-ceq $packageProvenance.SHA256 -and (Get-Item $packagePath).Length-eq $packageProvenance.Bytes) 'Package provenance differs.'
Add-Type -AssemblyName System.IO.Compression.FileSystem;$zip=[IO.Compression.ZipFile]::OpenRead($packagePath);try{$entry=@($zip.Entries|Where-Object FullName -CEQ 'FancyWM.GUI/FancyWM.dll');Require($entry.Count-eq 1) 'Embedded FancyWM.dll missing.';$stream=$entry[0].Open();try{$memory=[IO.MemoryStream]::new();$stream.CopyTo($memory);$dllBytes=$memory.ToArray()}finally{$stream.Dispose()};$embeddedHash=[Convert]::ToHexString([Security.Cryptography.SHA256]::HashData($dllBytes));$peOffset=[BitConverter]::ToInt32($dllBytes,0x3c);$machine=[BitConverter]::ToUInt16($dllBytes,$peOffset+4);Require($machine-eq 0x8664 -and $embeddedHash-ceq $packageProvenance.EmbeddedFancyWMDllSHA256 -and $dllBytes.Length-eq $packageProvenance.EmbeddedFancyWMDllBytes) 'Embedded FancyWM.dll hash/architecture differs.'}finally{$zip.Dispose()}

$summary=[ordered]@{Verdict='ACCEPT';ReportVersion=1;SnapshotId=$SnapshotId;PerfId='PERF-030';BoundedStage='FocusHelper.RequestSequence.RunWorker removes the per-request current-state closure after controlled contention baseline';Commit=$head;Tree=$tree;SnapshotManifestSHA256=$c2.ManifestSHA256;SnapshotJSONSHA256=$c2.SnapshotSHA256;SnapshotSourceFiles=$c2.Manifest.Count;BaselineSnapshot=$BaselineSnapshotId;CandidateSnapshot=$CandidateSnapshotId;BaselineCandidateSourceDifferences=$r0c1;CandidateC2Differences=$c1c2;C1StrictReportSHA256=Hash $strictPath;MeasurementReverificationSHA256=Hash $reverificationPath;MeasurementsSHA256=Hash $measurementsPath;MeasurementRows=$rows.Count;AllocationPairs=15;WorkerTransitionAllocation=[ordered]@{BaselineBytes=24624;CandidateBytes=144;SavedBytes=24480;Transitions=255;SavedBytesPerTransition=96};FirstLazyDelegate=[ordered]@{FirstCallerBytes=368;WarmCallerBytes=304;LazyDelegateBytes=64};SemanticComparisons=400;Timing=[ordered]@{Wins=$strict.TimingWins;Losses=$strict.TimingLosses;Ties=$strict.TimingTies;AcceptanceGate=$false};CandidateTests=@($candidateTests);FullTests=@($fullTests);OptimizationLedger=[ordered]@{Rows=39820;Bytes=$append.NewLength;SHA256=$append.NewSHA256;PreviousRows=$append.OldRows;PreviousBytes=$append.OldLength;PreviousSHA256=$append.OldSHA256;AppendedRows=$append.AppendedRows;AppendedBytes=$append.SuffixLength;AppendedSHA256=$append.SuffixSHA256;AppendProofSHA256=Hash $appendPath};DependencyReplay=[ordered]@{SnapshotId=$DependencySnapshotId;PinnedCommit='adb9f55b84b567db9f6e0ee8df4c33d11a12d91f';BinarySHA256=$dependencyBinary[0].Hash;Evidence=$dependencyEvidence;NativeActionsPerformed=$false};ReleaseArtifact=[ordered]@{Path=$packageProvenance.Path;Bytes=$packageProvenance.Bytes;SHA256=$packageProvenance.SHA256;Source=$packageProvenance.Source;EmbeddedFancyWMDllPath='FancyWM.GUI/FancyWM.dll';EmbeddedFancyWMDllBytes=$dllBytes.Length;EmbeddedFancyWMDllSHA256=$embeddedHash;Architecture='x64';EmbeddedArchitecture='AMD64 PE32+';ProvenanceSHA256=Hash $packageProvenancePath;Installed=$false;Launched=$false;Published=$false};FunctionalDocuments=[ordered]@{TODO='C5AE4822AC1B62A92E66FE4C282035CD441F096CD93358DCE2E79119972C61D1';IMPLEMENTATION_STATUS='580E05F35A0D6EEE150B175E7886FC87F2B2FAB76025B498BC656A7E9830335D'};NativePreflight=[ordered]@{SnapshotId='FWM-ANIMATION-NATIVE-BASELINE-20260908-N1';Verdict='NATIVE_BLOCKED';SummarySHA256='B04F981CDC37B0B57EF8F46CC1A5C617FBEDBBE7800575F6EDEBE2621CAF79C7';CPU='NOT_MEASURED';GPU='NOT_MEASURED';PresentationLatency='NOT_MEASURED'};Limitations='Controlled managed contention and fake INative ownership/count evidence. Lock timing is scheduling-sensitive and descriptive. Native UIA/focus timeout, late activation, worker handles, production scheduling, process CPU/GPU, COM/WPF/DPI and presentation latency remain E2E_PENDING / NOT_MEASURED.';SummaryWriterSHA256=Hash $PSCommandPath;CreatedUtc=[DateTimeOffset]::UtcNow.ToString('o')}
$summary|ConvertTo-Json -Depth 10|Set-Content $summaryPath;$summary|ConvertTo-Json -Depth 10
