param(
    [Parameter(Mandatory)][string]$CandidateSnapshotId,
    [Parameter(Mandatory)][string]$BaselineSnapshotId,
    [Parameter(Mandatory)][string]$ExperimentId
)
$ErrorActionPreference='Stop'; Set-StrictMode -Version Latest
function Require([bool]$Condition,[string]$Message){if(!$Condition){throw $Message}}
function HashFile([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}
$repositoryRoot=(& git -C $PSScriptRoot rev-parse --show-toplevel).Trim();$candidateRoot=Join-Path $repositoryRoot "artifacts/performance/$CandidateSnapshotId";$baselineRoot=Join-Path $repositoryRoot "artifacts/performance/$BaselineSnapshotId";$experimentRoot=Join-Path $candidateRoot $ExperimentId;$outputPath=Join-Path $candidateRoot 'validation/keybindings-page-strict-verification.json';Require(!(Test-Path $outputPath))'Strict report exists.'
$candidateManifest=@(Import-Csv (Join-Path $candidateRoot 'manifest.csv'));$baselineManifest=@(Import-Csv (Join-Path $baselineRoot 'manifest.csv'));foreach($record in $candidateManifest){Require((HashFile(Join-Path $candidateRoot "source/$($record.Path)"))-ceq $record.SHA256)"Candidate source differs: $($record.Path)"};foreach($record in $baselineManifest){Require((HashFile(Join-Path $baselineRoot "source/$($record.Path)"))-ceq $record.SHA256)"Baseline source differs: $($record.Path)"}
$verifier=@($candidateManifest|Where-Object Path -CEQ 'scripts/performance/Verify-KeybindingsPageTooltip.ps1');Require($verifier.Count-eq 1 -and $verifier[0].SHA256-ceq(HashFile $PSCommandPath))'Verifier differs.';$fixturePath='FancyWM.Tests/Utilities/KeybindingsPageMaterializationTest.cs';Require(@($candidateManifest|Where-Object Path -CEQ $fixturePath)[0].SHA256-ceq @($baselineManifest|Where-Object Path -CEQ $fixturePath)[0].SHA256)'A/B fixture differs.'
$sourceChanges=@();$baseMap=@{};$baselineManifest|ForEach-Object{$baseMap[$_.Path]=$_.SHA256};foreach($record in $candidateManifest){if(!$baseMap.ContainsKey($record.Path)-or $baseMap[$record.Path]-cne $record.SHA256){$sourceChanges+=$record.Path}};Require($sourceChanges.Count-eq 1 -and $sourceChanges[0]-ceq 'FancyWM/Pages/Settings/KeybindingsPage.xaml')'Production source delta differs.'
$rows=@(Import-Csv (Join-Path $experimentRoot 'measurements.csv'));$raw=@(Import-Csv (Join-Path $experimentRoot 'raw-counters.csv'));$processes=@(Import-Csv (Join-Path $experimentRoot 'process-times.csv'));$checks=@(Import-Csv (Join-Path $experimentRoot 'binary-checks.csv'));$provenance=Get-Content -Raw (Join-Path $experimentRoot 'provenance.json')|ConvertFrom-Json
Require($rows.Count-eq 480 -and $raw.Count-eq 480 -and $processes.Count-eq 10 -and $provenance.Verdict-ceq 'MEASUREMENT_CHECKS_PASS')'Evidence dimensions differ.';Require($provenance.MeasurementsSHA256-ceq(HashFile(Join-Path $experimentRoot 'measurements.csv')) -and $provenance.RawCountersSHA256-ceq(HashFile(Join-Path $experimentRoot 'raw-counters.csv')) -and $provenance.ProcessTimesSHA256-ceq(HashFile(Join-Path $experimentRoot 'process-times.csv')) -and $provenance.BinaryChecksSHA256-ceq(HashFile(Join-Path $experimentRoot 'binary-checks.csv')))'Evidence hash differs.'
Require(@($checks|Where-Object{($_.Path-ceq 'FancyWM.dll')-ne($_.CandidateSHA256-cne $_.BaselineSHA256)}).Count-eq 0 -and @($checks|Where-Object Path -CEQ 'FancyWM.dll').Count-eq 1)'Binary delta differs.'
$allocationWins=0;$timingWins=0;$timingLosses=0;$semanticComparisons=0
foreach($pair in 1..5){foreach($count in 1,10,50){$b=@($raw|Where-Object{[int]$_.Pair-eq $pair-and$_.Variant-ceq'baseline'-and[int]$_.BindingsPerGroup-eq$count});$c=@($raw|Where-Object{[int]$_.Pair-eq $pair-and$_.Variant-ceq'candidate'-and[int]$_.BindingsPerGroup-eq$count});Require($b.Count-eq16-and$c.Count-eq16)'Counter group differs.';$bv=@{};$cv=@{};$b|ForEach-Object{$bv[$_.Metric]=[long]$_.Value};$c|ForEach-Object{$cv[$_.Metric]=[long]$_.Value};Require($cv['layout-bytes']-lt$bv['layout-bytes'])"Layout allocation did not improve: $pair/$count";$allocationWins++;if(($cv['constructor-ticks']+$cv['layout-ticks'])-lt($bv['constructor-ticks']+$bv['layout-ticks'])){$timingWins++}else{$timingLosses++};foreach($metric in 'timestamp-frequency','groups','bindings','items-controls','key-press-boxes','description-hosts'){Require($cv[$metric]-eq$bv[$metric])"Semantic mismatch: $pair/$count/$metric";$semanticComparisons++};$expected=8*$count;Require($bv['eager-description-tooltip-elements']-eq$expected-and$cv['eager-description-tooltip-elements']-eq0-and$bv['description-tooltip-strings']-eq0-and$cv['description-tooltip-strings']-eq$expected)'Tooltip ownership differs.';Require($bv['text-blocks']-$cv['text-blocks']-eq$expected)'TextBlock delta differs.'}}
for($i=1;$i-lt$processes.Count;$i++){Require([DateTimeOffset]$processes[$i].StartedUtc-ge[DateTimeOffset]$processes[$i-1].FinishedUtc)'Processes overlap.'}
[xml]$baselineTrx=Get-Content -Raw (Join-Path $baselineRoot 'validation/Release-keybindings-page.trx');[xml]$candidateTrx=Get-Content -Raw (Join-Path $candidateRoot 'validation/Release-keybindings-page.trx');$baselineAll=@($baselineTrx.SelectNodes("//*[local-name()='UnitTestResult']"));$candidateAll=@($candidateTrx.SelectNodes("//*[local-name()='UnitTestResult']"));$baselineLeaves=@($baselineAll|Where-Object{$_.SelectNodes("./*[local-name()='InnerResults']/*[local-name()='UnitTestResult']").Count-eq0});$candidateLeaves=@($candidateAll|Where-Object{$_.SelectNodes("./*[local-name()='InnerResults']/*[local-name()='UnitTestResult']").Count-eq0});Require($baselineLeaves.Count-eq2-and@($baselineLeaves|Where-Object outcome -CNE 'Passed').Count-eq1-and$candidateLeaves.Count-eq2-and@($candidateLeaves|Where-Object outcome -CNE 'Passed').Count-eq0)'Red/green fixture differs.'
$report=[ordered]@{Verdict='ACCEPT';Accepted=$true;PerfId='PERF-032';CandidateSnapshotId=$CandidateSnapshotId;BaselineSnapshotId=$BaselineSnapshotId;ExperimentId=$ExperimentId;Rows=$rows.Count;Pairs=5;Processes=10;LayoutAllocationWins=$allocationWins;CombinedTimingWins=$timingWins;CombinedTimingLosses=$timingLosses;SemanticComparisons=$semanticComparisons;BaselineRed='1 pass / 1 tooltip-ownership fail';CandidateGreen='2/2';NativeCalls=$false;MeasurementsSHA256=HashFile(Join-Path $experimentRoot 'measurements.csv');RawCountersSHA256=HashFile(Join-Path $experimentRoot 'raw-counters.csv');ProcessTimesSHA256=HashFile(Join-Path $experimentRoot 'process-times.csv');BinaryChecksSHA256=HashFile(Join-Path $experimentRoot 'binary-checks.csv');VerifierSHA256=HashFile $PSCommandPath;CreatedUtc=[DateTimeOffset]::UtcNow.ToString('o')};New-Item -ItemType Directory -Force (Split-Path $outputPath)|Out-Null;[IO.File]::WriteAllText($outputPath,(($report|ConvertTo-Json -Depth 5)+"`n"),[Text.UTF8Encoding]::new($false));$report|ConvertTo-Json -Depth 5
